AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Serverless Function
Outputs: {}
Resources:
  ExampleSAMLocaldev:
    Properties:
      AutoPublishAlias: dev
      CodeUri: s3://lh-lambda-deploy/example-s-a-m-local-dev/2018-05-10/6c5d1a1ed713ae4ca693611447393138
      DeploymentPreference:
        Type: AllAtOnce
      Description: AWS Serverless Function
      FunctionName: ExampleSAMLocaldev
      Handler: ExampleSAMLocaldev
      Role:
        Fn::GetAtt:
        - ExampleSAMLocaldevRole
        - Arn
      Runtime: go1.x
      Tags:
        FunctionGroup: ExampleSAMLocal
        Stage: dev
      Timeout: 30
    Type: AWS::Serverless::Function
  ExampleSAMLocaldevRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
        Version: '2012-10-17'
      Path: /
      Policies:
      - PolicyDocument:
          Statement:
          - Action:
            - logs:CreateLogStream
            - logs:CreateLogGroup
            - logs:PutLogEvents
            Effect: Allow
            Resource: arn:aws:logs:*:*:*
          Version: '2012-10-17'
        PolicyName: CloudWatchLogs
      RoleName: ExampleSAMLocaldevRole
    Type: AWS::IAM::Role
Transform: AWS::Serverless-2016-10-31
