AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Serverless Function
Resources:
  ExampleLambdaApi:
    Properties:
      AutoPublishAlias: live
      CodeUri: s3://lambda-example-lambda-api/dd97c7e991ffa5e39476d73a8fb8d8e9
      DeploymentPreference:
        Alarms:
        - '!Ref AliasErrorMetricGreaterThanZeroAlarm'
        - '!Ref LatestVersionErrorMetricGreaterThanZeroAlarm'
        Hooks:
          PostTraffic: '!Ref PostTrafficLambdaFunction'
          PreTraffic: '!Ref PreTrafficLambdaFunction'
        Type: Canary10Percent10Minutes
      Description: AWS Serverless Function
      FunctionName: ExampleLambdaApi
      Handler: ExampleLambdaApi
      Role: arn:aws:iam::842913648961:role/lambda_basic_execution
      Runtime: go1.x
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
