AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Function
Resources:
  ExampleLambdaApi:
    Type: AWS::Serverless::Function
    Properties:
      AutoPublishAlias: live
      CodeUri: ./ExampleLambdaApi.zip
      DeploymentPreference:
        Alarms:
        - '!Ref AliasErrorMetricGreaterThanZeroAlarm'
        - '!Ref LatestVersionErrorMetricGreaterThanZeroAlarm'
        Hooks:
          PostTraffic: '!Ref PostTrafficLambdaFunction'
          PreTraffic: '!Ref PreTrafficLambdaFunction'
        Type: Canary10Percent10Minutes
      Description: AWS Serverless Function
      Events:
        ExampleLambdaApi:
          Properties:
            Method: any
            Path: /{proxy+}
          Type: Api
      FunctionName: ExampleLambdaApi
      Handler: ExampleLambdaApi
      Role: arn:aws:iam::842913648961:role/lambda-gateway-execution-role
      Runtime: go1.x
