AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Serverless Function
Resources:
  ExampleLambdaBasic:
    Properties:
      CodeUri: s3://lambda-example-lambda-basic/e7460495f3b7ae75e6bafc07d1c46af4
      Description: AWS Serverless Function
      FunctionName: ExampleLambdaBasic
      Handler: ExampleLambdaBasic
      Role: arn:aws:iam::842913648961:role/lambda_basic_execution
      Runtime: go1.x
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
