AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Serverless Function
Resources:
  ExampleLambdaBasic:
    Properties:
      AutoPublishAlias: live
      CodeUri: s3://lambda-example-lambda-basic/2cefb1aa8894461e481f4dbcd77b3eb7
      DeploymentPreference:
        Alarms:
        - '!Ref AliasErrorMetricGreaterThanZeroAlarm'
        - '!Ref LatestVersionErrorMetricGreaterThanZeroAlarm'
        Hooks:
          PostTraffic: '!Ref PostTrafficLambdaFunction'
          PreTraffic: '!Ref PreTrafficLambdaFunction'
        Type: Canary10Percent10Minutes
      Description: AWS Serverless Function
      FunctionName: ExampleLambdaBasic
      Handler: ExampleLambdaBasic
      Role: arn:aws:iam::842913648961:role/lambda_basic_execution
      Runtime: go1.x
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
