AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Function
Resources:
  ExampleLambdaBasic:
    Type: AWS::Serverless::Function
    Properties:
      AutoPublishAlias: live
      CodeUri: ./ExampleLambdaBasic.zip
      DeploymentPreference:
        Alarms:
        - '!Ref AliasErrorMetricGreaterThanZeroAlarm'
        - '!Ref LatestVersionErrorMetricGreaterThanZeroAlarm'
        Hooks:
          PostTraffic: '!Ref PostTrafficLambdaFunction'
          PreTraffic: '!Ref PreTrafficLambdaFunction'
        Type: Canary10Percent10Minutes
      Description: AWS Serverless Function
      FunctionName: ExampleLambdaBasic
      Handler: ExampleLambdaBasic
      Role: arn:aws:iam::842913648961:role/lambda_basic_execution
      Runtime: go1.x
