AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Serverless Function
Outputs:
  ApiUrl:
    Description: ExampleXRayprod(prod) Api URL
    Value:
      Fn::Sub: https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/prod
Resources:
  ApiAccessPermission:
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Ref: ExampleXRayprod
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Sub: arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGatewayApi}/prod/*/*
    Type: AWS::Lambda::Permission
  ApiGatewayApi:
    Properties:
      DefinitionBody:
        basePath: /prod
        info:
          title: ExampleXRayprod
          version: '1.0'
        paths:
          /{proxy+}:
            x-amazon-apigateway-any-method:
              produces:
              - application/json
              x-amazon-apigateway-integration:
                httpMethod: POST
                passthroughBehavior: when_no_match
                type: aws_proxy
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ExampleXRayprod.Arn}/invocations
        schemes:
        - https
        swagger: '2.0'
      Name: ExampleXRayprod
      StageName: prod
    Type: AWS::Serverless::Api
  ExampleXRayprod:
    Properties:
      AutoPublishAlias: prod
      CodeUri: s3://lambda-example-x-ray-prod/2018-05-03/cfdc7a5180885dcade36804ba233cfc6
      DeploymentPreference:
        Type: Canary10Percent10Minutes
      Description: AWS Serverless Function
      Events:
        ApiEvent:
          Properties:
            Method: ANY
            Path: /{proxy+}
            RestApiId:
              Ref: ApiGatewayApi
          Type: Api
      FunctionName: ExampleXRayprod
      Handler: ExampleXRayprod
      Role:
        Fn::GetAtt:
        - ExampleXRayprodRole
        - Arn
      Runtime: go1.x
      Timeout: 30
    Type: AWS::Serverless::Function
  ExampleXRayprodRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
        Version: '2012-10-17'
      Path: /
      Policies:
      - PolicyDocument:
          Statement:
          - Action:
            - logs:CreateLogStream
            - logs:CreateLogGroup
            - logs:PutLogEvents
            Effect: Allow
            Resource: arn:aws:logs:*:*:*
          Version: '2012-10-17'
        PolicyName: CloudWatchLogs
      - PolicyDocument:
          Statement:
          - Action:
            - xray:*
            Effect: Allow
            Resource: '*'
          Version: '2012-10-17'
        PolicyName: XRayFullAccess
      RoleName: ExampleXRayprodRole
    Type: AWS::IAM::Role
Transform: AWS::Serverless-2016-10-31
