AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Function
Resources:
  ExampleLambdaBasic:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./ExampleLambdaBasic.zip
      Description: AWS Serverless Function
      FunctionName: ExampleLambdaBasic
      Handler: ExampleLambdaBasic
      Role: lambda_basic_execution
      Runtime: go1.x
