AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Function
Resources:
  ApiAccessPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Ref: ExampleTestIAMUserdev
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Sub: arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGatewayApi}/dev/*/*
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      DefinitionBody:
        basePath: /dev
        info:
          title: ExampleTestIAMUserdev
          version: "1.0"
        paths:
          /{proxy+}:
            x-amazon-apigateway-any-method:
              produces:
              - application/json
              x-amazon-apigateway-integration:
                httpMethod: POST
                passthroughBehavior: when_no_match
                type: aws_proxy
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ExampleTestIAMUserdev.Arn}/invocations
        schemes:
        - https
        swagger: "2.0"
      Name: ExampleTestIAMUserdev
      StageName: dev
  ExampleTestIAMUserdev:
    Type: AWS::Serverless::Function
    Properties:
      AutoPublishAlias: dev
      CodeUri: ./ExampleTestIAMUserdev.zip
      DeploymentPreference:
        Type: AllAtOnce
      Description: AWS Serverless Function
      Events:
        ApiEvent:
          Properties:
            Method: ANY
            Path: /{proxy+}
            RestApiId:
              Ref: ApiGatewayApi
          Type: Api
      FunctionName: ExampleTestIAMUserdev
      Handler: ExampleTestIAMUserdev
      Role:
        Fn::GetAtt:
        - ExampleTestIAMUserdevRole
        - Arn
      Runtime: go1.x
      Tags:
        FunctionGroup: ExampleTestIAMUser
        Stage: dev
      Timeout: 30
  ExampleTestIAMUserdevRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: /
      Policies:
      - PolicyName: CloudWatchLogs
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogStream
            - logs:CreateLogGroup
            - logs:PutLogEvents
            Resource: arn:aws:logs:*:*:*
      - PolicyName: XRayFullAccess
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Effect: Allow
            Action:
            - xray:*
            Resource: '*'
      RoleName: ExampleTestIAMUserdevRole
Outputs:
  ApiUrl:
    Description: ExampleTestIAMUserdev(dev) Api URL
    Value:
      Fn::Sub: https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/dev
